name: flutter_escpos_printer
description: A demo Flutter app for ESC/POS network printing.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  esc_pos_printer: ^3.1.1
  esc_pos_utils: ^1.1.0
  permission_handler: ^11.0.1

flutter:
  uses-material-design: true
